# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 220, 47, 13))
        self.label_3.setObjectName("label_3")
        self.txtI = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtI.setGeometry(QtCore.QRect(130, 120, 431, 71))
        self.txtI.setObjectName("txtI")
        self.txtS = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtS.setGeometry(QtCore.QRect(130, 230, 431, 71))
        self.txtS.setObjectName("txtS")
        self.btnS = QtWidgets.QPushButton(self.centralwidget)
        self.btnS.setGeometry(QtCore.QRect(170, 340, 75, 23))
        self.btnS.setObjectName("btnS")
        self.btnV = QtWidgets.QPushButton(self.centralwidget)
        self.btnV.setGeometry(QtCore.QRect(390, 340, 75, 23))
        self.btnV.setObjectName("btnV")
        self.btnG = QtWidgets.QPushButton(self.centralwidget)
        self.btnG.setGeometry(QtCore.QRect(390, 60, 75, 23))
        self.btnG.setObjectName("btnG")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ECC CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Info"))
        self.label_3.setText(_translate("MainWindow", "Sign"))
        self.btnS.setText(_translate("MainWindow", "Sign"))
        self.btnV.setText(_translate("MainWindow", "Verify"))
        self.btnG.setText(_translate("MainWindow", "Gen Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
