# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 432)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.tddju = QtWidgets.QLabel(self.centralwidget)
        self.tddju.setGeometry(QtCore.QRect(30, 220, 51, 16))
        self.tddju.setObjectName("tddju")
        self.Information = QtWidgets.QLabel(self.centralwidget)
        self.Information.setGeometry(QtCore.QRect(350, 110, 61, 16))
        self.Information.setObjectName("Information")
        self.lab_04 = QtWidgets.QLabel(self.centralwidget)
        self.lab_04.setGeometry(QtCore.QRect(360, 220, 47, 13))
        self.lab_04.setObjectName("lab_04")
        self.txtPlantext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtPlantext.setGeometry(QtCore.QRect(90, 110, 231, 71))
        self.txtPlantext.setObjectName("txtPlantext")
        self.txtCiphertext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtCiphertext.setGeometry(QtCore.QRect(90, 220, 231, 71))
        self.txtCiphertext.setObjectName("txtCiphertext")
        self.txtInformation = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtInformation.setGeometry(QtCore.QRect(410, 110, 251, 71))
        self.txtInformation.setObjectName("txtInformation")
        self.txtSignature = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtSignature.setGeometry(QtCore.QRect(410, 220, 251, 71))
        self.txtSignature.setObjectName("txtSignature")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(50, 330, 75, 23))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(200, 330, 75, 23))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.btnSign = QtWidgets.QPushButton(self.centralwidget)
        self.btnSign.setGeometry(QtCore.QRect(380, 330, 75, 23))
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerify.setGeometry(QtCore.QRect(550, 330, 75, 23))
        self.btnVerify.setObjectName("btnVerify")
        self.btnGenerateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerateKeys.setGeometry(QtCore.QRect(410, 50, 81, 23))
        self.btnGenerateKeys.setObjectName("btnGenerateKeys")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA  CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plantext"))
        self.tddju.setText(_translate("MainWindow", "Ciphertext"))
        self.Information.setText(_translate("MainWindow", "Information"))
        self.lab_04.setText(_translate("MainWindow", "Signature"))
        self.btnEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btnSign.setText(_translate("MainWindow", "Sign"))
        self.btnVerify.setText(_translate("MainWindow", "Verify"))
        self.btnGenerateKeys.setText(_translate("MainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
